FROM mongo:latest

ENV MONGO_INITDB_DATABASE resume_database

# If you need to run any initialization scripts, you can add them here
# COPY init-mongo.sh /docker-entrypoint-initdb.d/
# CMD ["mongod", "--bind_ip_all"]